canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
color="blue";
ctx.beginPath();
ctx.strokeStyle= color;
ctx.lineWidth= 2;
ctx.arc(200, 200, 40, 0, 2* Math.PI);
ctx.stroke();
color="yellow";
ctx.beginPath();
ctx.strokeStyle= color;
ctx.lineWidth= 2;
ctx.arc(240, 250, 40, 0, 2* Math.PI);
ctx.stroke();
color="black";
ctx.beginPath();
ctx.strokeStyle= color;
ctx.lineWidth= 2;
ctx.arc(290, 200, 40, 0, 2* Math.PI);
ctx.stroke();
color="green";
ctx.beginPath();
ctx.strokeStyle= color;
ctx.lineWidth= 2;
ctx.arc(340, 250, 40, 0, 2* Math.PI);
ctx.stroke();
color="red";
ctx.beginPath();
ctx.strokeStyle= color;
ctx.lineWidth= 2;
ctx.arc(380, 200, 40, 0, 2* Math.PI);
ctx.stroke();
